"""initial_migration

Revision ID: b98031386503
Revises: 
Create Date: 2025-11-22 11:12:02.912954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98031386503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nidn', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='dosenstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nidn')
    )
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kelas', sa.String(length=10), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DO', 'CUTI', 'LULUS', 'INACTIVE', name='mahasiswastatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mata_kuliah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_mk', sa.String(length=20), nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='matakuliahstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_mk')
    )
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('ruangan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'DONE', name='jadwalstatus'), nullable=False),
    sa.Column('mata_kuliah_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tugas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='statustugas'), nullable=False),
    sa.Column('mata_kuliah_id', sa.Integer(), nullable=True),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tugas')
    op.drop_table('jadwal')
    op.drop_table('mata_kuliah')
    op.drop_table('mahasiswa')
    op.drop_table('dosen')
    # ### end Alembic commands ###
