name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  do-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "uvicorn[standard]" # Ensure uvicorn is installed with standard dependencies for running tests

    - name: Create .env file for CI
      run: |
        echo "DB_URL=sqlite:///./test.db" > .env

    - name: Run Code Formatter (Black) - Check only
      run: |
        black src/ tests/ manage.py --check

    - name: Run Import Sorter (Isort) - Check only
      run: |
        isort src/ tests/ manage.py --check-only

    - name: Run Linting (Flake8)
      run: |
        flake8 src/ tests/ manage.py

    - name: Run Static Type Checking (MyPy)
      run: |
        mypy src/

    - name: Run Unit and API Tests with Coverage
      run: |
        pytest tests/unit/ tests/api/ --cov=src --cov-report=xml --cov-report=term-missing
